-- MySQL Script generated by MySQL Workbench
-- Tue Nov  3 20:37:40 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema workly
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema workly
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `workly` DEFAULT CHARACTER SET utf8 ;
USE `workly` ;

-- -----------------------------------------------------
-- Table `workly`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workly`.`usuarios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `logo` VARCHAR(200) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workly`.`experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workly`.`experiencia` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(250) NOT NULL,
  `tiempo` VARCHAR(45) NOT NULL,
  `usuario_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workly`.`vacantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workly`.`vacantes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(250) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `salario` VARCHAR(20) NOT NULL,
  `usuario_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workly`.`idiomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workly`.`idiomas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workly`.`idiomas_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workly`.`idiomas_usuarios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(10) UNSIGNED NOT NULL,
  `idiomas_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workly`.`habilidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workly`.`habilidades` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workly`.`habilidades_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workly`.`habilidades_usuarios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(10) UNSIGNED NOT NULL,
  `habilidades_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
